package com.apiguard.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * A pre-computed daily/monthly usage snapshot, generated by a scheduled
 * job so the dashboard can show historical reports without re-aggregating
 * the entire request_logs table every time.
 */
@Entity
@Table(name = "usage_reports")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UsageReport {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private LocalDate reportDate;

    @Column(nullable = false)
    private long totalRequests;

    @Column(nullable = false)
    private long failedRequests;

    @Column(nullable = false)
    private double averageResponseTimeMs;

    @Column(nullable = false)
    private LocalDateTime generatedAt;
}
